### PR TITLE
FHIR-33860: Add authors to the credits list

### PR DESCRIPTION
**Pull request by masnick**
Please comment here if you would like to be added with the name and affiliation you'd like to use.

### CODE REVIEW

**Comment by jmandel** [comment]
Josh Mandel, SMART Health IT and Microsoft

**Comment by Shaumik-Ashraf** [comment]
Shaumik Ashraf, The MITRE Corporation

**Comment by p2-apple** [comment]
Ricky Bloomfield, Apple Inc.
Pascal Pfiffner, Apple Inc.
Cary Anderson, Apple Inc.

**Comment by nkarip** [comment]
Neelima Karipineni (The MITRE Corporation)

**Comment by radamson** [comment]
Reece Adamson (The MITRE Corporation)

**Comment by jpp9** [comment]
JP Pollak (The Commons Project and Cornell)

**Pull request merged**
